// Safa Shipping Console — shared ERP schema (server + browser)
// Each entity: collection fields with type, Arabic label, options, reference and rules.
(function (root) {
  const O = (...pairs) => pairs; // [value, label, tone]
  const MODES = O(['SE', 'بحري تصدير', 'blue'], ['SI', 'بحري استيراد', 'blue'], ['LE', 'بري تصدير', 'amber'], ['LI', 'بري استيراد', 'amber'], ['LT', 'بري ترانزيت', 'amber'], ['CC', 'تخليص جمركي', 'green']);
  const CUR = O(['USD', 'دولار أمريكي'], ['EUR', 'يورو'], ['SAR', 'ريال سعودي'], ['AED', 'درهم إماراتي'], ['SYP', 'ليرة سورية'], ['JOD', 'دينار أردني'], ['TRY', 'ليرة تركية']);

  const MODULES = [
    ['crm', 'إدارة علاقات العملاء', 'users'], ['contracts', 'إدارة العقود', 'contract'], ['ops', 'العمليات والشحنات', 'truck'],
    ['customs', 'التخليص الجمركي', 'ship'], ['finance', 'المالية والمحاسبة', 'calc'], ['branches', 'الفروع والوكلاء', 'network'],
    ['warehouse', 'المستودعات واللوجستيات', 'warehouse'], ['fleet', 'إدارة الأسطول', 'truck'], ['procurement', 'المشتريات والموردين', 'cart'],
    ['hr', 'الموارد البشرية', 'users'], ['documents', 'إدارة المستندات', 'doc'], ['quality', 'إدارة الجودة ISO 9001', 'shield'],
    ['reports', 'التقارير وذكاء الأعمال', 'chart'], ['settings', 'المستخدمون والصلاحيات والإعدادات', 'gear'],
  ];

  const E = {
    parties: { module: 'crm', label: 'جهة', search: ['name', 'contact', 'phone', 'email', 'city', 'taxNo', 'code'], num: { prefix: 'CUST', field: 'code', pad: 6 },
      fields: {
        code: { t: 'str', label: 'رمز الجهة', auto: true },
        name: { t: 'str', label: 'الاسم', req: true, full: true },
        type: { t: 'enum', label: 'النوع', opts: O(['customer', 'عميل'], ['agent', 'وكيل بالخارج'], ['carrier', 'ناقل / خط ملاحي'], ['trucking', 'شركة نقل بري'], ['broker', 'مخلص جمركي'], ['supplier', 'مورد']) },
        category: { t: 'enum', label: 'الفئة', opts: O(['company', 'شركة'], ['org', 'مؤسسة'], ['individual', 'فرد'], ['gov', 'جهة حكومية']) },
        status: { t: 'enum', label: 'الحالة', opts: O(['active', 'نشط', 'green'], ['inactive', 'غير نشط', ''], ['blocked', 'موقوف', 'red']) },
        branchId: { t: 'ref', label: 'الفرع', ref: 'branches' },
        contact: { t: 'str', label: 'الشخص المسؤول' }, phone: { t: 'str', label: 'الهاتف', dir: 'ltr' }, email: { t: 'str', label: 'البريد الإلكتروني', dir: 'ltr' },
        country: { t: 'str', label: 'الدولة' }, city: { t: 'str', label: 'المدينة' }, address: { t: 'text', label: 'العنوان' },
        taxNo: { t: 'str', label: 'الرقم الضريبي / السجل', dir: 'ltr' },
        creditLimit: { t: 'num', label: 'حد الائتمان' }, paymentTerms: { t: 'int', label: 'مدة السداد (يوم)' },
        rating: { t: 'num', label: 'تقييم المورد (1-5)' }, notes: { t: 'text', label: 'ملاحظات' },
      } },
    interactions: { module: 'crm', label: 'تواصل', search: ['subject', 'summary'],
      fields: {
        partyId: { t: 'ref', label: 'العميل', ref: 'parties', req: true },
        date: { t: 'dt', label: 'التاريخ والوقت' },
        type: { t: 'enum', label: 'نوع التواصل', opts: O(['call', 'مكالمة'], ['email', 'بريد إلكتروني'], ['meeting', 'اجتماع'], ['whatsapp', 'واتساب'], ['visit', 'زيارة']) },
        subject: { t: 'str', label: 'الموضوع', req: true, full: true }, summary: { t: 'text', label: 'ملخص التواصل' },
        nextAction: { t: 'str', label: 'الإجراء التالي' }, nextDate: { t: 'date', label: 'موعد المتابعة' },
      } },
    quotes: { module: 'crm', label: 'عرض سعر', search: ['no', 'origin', 'destination', 'cargo'], num: { prefix: 'QT', field: 'no' },
      fields: {
        no: { t: 'str', label: 'رقم العرض', auto: true },
        partyId: { t: 'ref', label: 'العميل', ref: 'parties', req: true },
        date: { t: 'date', label: 'تاريخ العرض' }, validUntil: { t: 'date', label: 'صالح حتى' },
        mode: { t: 'enum', label: 'نوع الخدمة', opts: MODES },
        origin: { t: 'str', label: 'من' }, destination: { t: 'str', label: 'إلى' }, cargo: { t: 'text', label: 'وصف البضاعة' },
        currency: { t: 'enum', label: 'العملة', opts: CUR },
        items: { t: 'items', label: 'بنود العرض' },
        total: { t: 'num', label: 'القيمة', calc: true },
        status: { t: 'enum', label: 'الحالة', opts: O(['draft', 'مسودة', ''], ['requested', 'طلب من العميل', 'amber'], ['sent', 'مرسل', 'blue'], ['accepted', 'مقبول', 'green'], ['rejected', 'مرفوض', 'red'], ['expired', 'منتهي', '']) },
        jobId: { t: 'ref', label: 'ملف الشحن', ref: 'jobs' }, notes: { t: 'text', label: 'ملاحظات وشروط' },
      } },
    contracts: { module: 'contracts', label: 'عقد', search: ['no', 'title'], num: { prefix: 'CTR', field: 'no' },
      fields: {
        no: { t: 'str', label: 'رقم العقد', auto: true },
        partyId: { t: 'ref', label: 'العميل أو الطرف', ref: 'parties', req: true },
        title: { t: 'str', label: 'عنوان العقد', full: true },
        type: { t: 'enum', label: 'النوع', opts: O(['transport', 'خدمات نقل بري'], ['sea', 'خدمات شحن بحري'], ['customs', 'خدمات تخليص'], ['logistics', 'خدمات لوجستية متكاملة'], ['warehousing', 'خدمات تخزين'], ['fleet', 'تأجير أسطول'], ['service', 'اتفاقية مستوى خدمة SLA']) },
        value: { t: 'num', label: 'القيمة' }, currency: { t: 'enum', label: 'العملة', opts: CUR },
        start: { t: 'date', label: 'تاريخ البداية' }, end: { t: 'date', label: 'تاريخ الانتهاء' },
        state: { t: 'enum', label: 'وضع العقد', opts: O(['active', 'ساري', 'green'], ['review', 'قيد المراجعة', 'blue'], ['draft', 'مسودة', ''], ['terminated', 'منتهٍ بالإلغاء', 'red']) },
        renewal: { t: 'bool', label: 'تجديد تلقائي' }, notes: { t: 'text', label: 'ملاحظات' },
      } },
    jobs: { module: 'ops', label: 'شحنة', search: ['no', 'shipper', 'consignee', 'origin', 'destination', 'mbl', 'hbl', 'cmr', 'bookingNo', 'declNo', 'vessel'],
      fields: {
        mode: { t: 'enum', label: 'نوع الخدمة', opts: MODES, req: true },
        service: { t: 'enum', label: 'نمط الشحن', opts: O(['', '—'], ['FCL', 'حاوية كاملة FCL'], ['LCL', 'شحن جزئي LCL'], ['FTL', 'شاحنة كاملة FTL'], ['LTL', 'شحن بري جزئي LTL'], ['BULK', 'بضائع سائبة'], ['RORO', 'دحرجة RoRo']) },
        customerId: { t: 'ref', label: 'العميل', ref: 'parties', req: true }, branchId: { t: 'ref', label: 'الفرع', ref: 'branches' },
        shipper: { t: 'str', label: 'الشاحن' }, consignee: { t: 'str', label: 'المستلم' },
        incoterm: { t: 'enum', label: 'الإنكوترم', opts: O(['', '—'], ['EXW', 'EXW'], ['FCA', 'FCA'], ['CPT', 'CPT'], ['CIP', 'CIP'], ['DAP', 'DAP'], ['DPU', 'DPU'], ['DDP', 'DDP'], ['FAS', 'FAS'], ['FOB', 'FOB'], ['CFR', 'CFR'], ['CIF', 'CIF']) },
        origin: { t: 'str', label: 'من (ميناء / مدينة)' }, destination: { t: 'str', label: 'إلى (ميناء / مدينة)' },
        originCountry: { t: 'str', label: 'بلد المنشأ' }, destCountry: { t: 'str', label: 'بلد الوجهة' },
        carrierId: { t: 'ref', label: 'الناقل / شركة النقل', ref: 'parties' }, agentId: { t: 'ref', label: 'الوكيل', ref: 'parties' }, brokerId: { t: 'ref', label: 'المخلص الجمركي', ref: 'parties' },
        vessel: { t: 'str', label: 'السفينة' }, voyage: { t: 'str', label: 'رقم الرحلة', dir: 'ltr' }, bookingNo: { t: 'str', label: 'رقم الحجز', dir: 'ltr' },
        mbl: { t: 'str', label: 'البوليصة الرئيسية MBL', dir: 'ltr' }, hbl: { t: 'str', label: 'البوليصة الفرعية HBL', dir: 'ltr' },
        cmr: { t: 'str', label: 'رقم CMR', dir: 'ltr' }, truckId: { t: 'ref', label: 'الشاحنة', ref: 'trucks' }, driverId: { t: 'ref', label: 'السائق', ref: 'drivers' },
        trailer: { t: 'str', label: 'رقم المقطورة', dir: 'ltr' }, border: { t: 'str', label: 'المنفذ الحدودي' },
        etd: { t: 'date', label: 'المغادرة المتوقعة ETD' }, eta: { t: 'date', label: 'الوصول المتوقع ETA' }, atd: { t: 'date', label: 'المغادرة الفعلية ATD' }, ata: { t: 'date', label: 'الوصول الفعلي ATA' },
        freeDays: { t: 'int', label: 'الأيام المجانية' },
        cargo: { t: 'text', label: 'وصف البضاعة' }, cargoType: { t: 'enum', label: 'نوع البضاعة', opts: O(['', '—'], ['general', 'بضائع عامة'], ['electronics', 'أجهزة إلكترونية'], ['food', 'مواد غذائية'], ['chemicals', 'مواد كيميائية'], ['machinery', 'آلات ومعدات'], ['textiles', 'منسوجات وملابس'], ['vehicles', 'مركبات'], ['dangerous', 'بضائع خطرة'], ['other', 'أخرى']) },
        packages: { t: 'int', label: 'عدد الطرود' }, pkgType: { t: 'str', label: 'نوع التعبئة' },
        grossKg: { t: 'num', label: 'الوزن الإجمالي (كغ)' }, cbm: { t: 'num', label: 'الحجم (م³)' }, dims: { t: 'str', label: 'الأبعاد (ط×ع×ر)' },
        hsCode: { t: 'str', label: 'البند الجمركي HS', dir: 'ltr' }, goodsValue: { t: 'num', label: 'قيمة البضاعة' }, goodsCurrency: { t: 'enum', label: 'عملة القيمة', opts: CUR },
        containers: { t: 'containers', label: 'الحاويات' },
        declNo: { t: 'str', label: 'رقم البيان الجمركي', dir: 'ltr' }, declDate: { t: 'date', label: 'تاريخ البيان' }, customsOffice: { t: 'str', label: 'المنفذ / المكتب الجمركي' },
        customsType: { t: 'enum', label: 'نوع المعاملة', opts: O(['', '—'], ['import', 'استيراد'], ['export', 'تصدير'], ['transit', 'عبور (ترانزيت)'], ['temp', 'إدخال مؤقت']) },
        channel: { t: 'enum', label: 'المسار الجمركي', opts: O(['', '—'], ['green', 'أخضر', 'green'], ['yellow', 'أصفر', 'amber'], ['red', 'أحمر', 'red']) },
        dutyAmount: { t: 'num', label: 'الرسوم والضرائب' },
        importer: { t: 'str', label: 'المستورد (الاسم القانوني)' }, importerTax: { t: 'str', label: 'الرقم الضريبي للمستورد', dir: 'ltr' },
        exporter: { t: 'str', label: 'المصدّر' }, exporterCountry: { t: 'str', label: 'دولة المصدّر' },
        assignedTo: { t: 'user', label: 'الموظف المسؤول' },
        priority: { t: 'enum', label: 'الأولوية', opts: O(['normal', 'عادية', ''], ['high', 'مرتفعة', 'amber'], ['urgent', 'عاجلة', 'red']) },
        notes: { t: 'text', label: 'ملاحظات' },
      } },
    tasks: { module: 'ops', label: 'مهمة', search: ['title', 'note'],
      fields: { jobId: { t: 'ref', label: 'الملف', ref: 'jobs' }, title: { t: 'str', label: 'عنوان المهمة', req: true }, due: { t: 'date', label: 'الموعد' },
        assignee: { t: 'user', label: 'المسؤول' }, done: { t: 'bool', label: 'منجزة' }, note: { t: 'text', label: 'ملاحظة' } } },
    costs: { module: 'ops', label: 'تكلفة', search: ['item', 'note'],
      fields: { jobId: { t: 'ref', label: 'الشحنة', ref: 'jobs', req: true },
        item: { t: 'enum', label: 'بند التكلفة', opts: O(['freight', 'أجور الشحن'], ['customs', 'رسوم التخليص'], ['port', 'رسوم الميناء'], ['trucking', 'النقل البري'], ['insurance', 'التأمين'], ['storage', 'التخزين'], ['demurrage', 'غرامات التأخير'], ['other', 'رسوم إضافية']) },
        partyId: { t: 'ref', label: 'الجهة (المورد)', ref: 'parties' }, amount: { t: 'num', label: 'المبلغ', req: true }, currency: { t: 'enum', label: 'العملة', opts: CUR },
        state: { t: 'enum', label: 'الحالة', opts: O(['pending', 'مستحقة', 'amber'], ['paid', 'مدفوعة', 'green']) }, note: { t: 'str', label: 'ملاحظات' } } },
    trips: { module: 'fleet', label: 'رحلة', search: ['no', 'from', 'to'], num: { prefix: 'TRP', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم الرحلة', auto: true }, jobId: { t: 'ref', label: 'الشحنة', ref: 'jobs' }, truckId: { t: 'ref', label: 'المركبة', ref: 'trucks' }, driverId: { t: 'ref', label: 'السائق', ref: 'drivers' },
        from: { t: 'str', label: 'من' }, to: { t: 'str', label: 'إلى' }, depart: { t: 'dt', label: 'موعد المغادرة', req: true }, arrive: { t: 'dt', label: 'موعد الوصول المتوقع' },
        km: { t: 'num', label: 'المسافة (كم)' },
        state: { t: 'enum', label: 'الحالة', opts: O(['planned', 'مجدولة', 'blue'], ['on_road', 'في الطريق', 'amber'], ['done', 'مكتملة', 'green'], ['cancelled', 'ملغاة', 'red']) }, notes: { t: 'text', label: 'ملاحظات' } } },
    invoices: { module: 'finance', label: 'فاتورة', search: ['no', 'poNo', 'serviceRef'], num: { prefix: 'INV', field: 'no' },
      fields: {
        no: { t: 'str', label: 'رقم الفاتورة', auto: true },
        partyId: { t: 'ref', label: 'الجهة المستلمة', ref: 'parties', req: true }, jobId: { t: 'ref', label: 'الشحنة', ref: 'jobs' },
        date: { t: 'date', label: 'تاريخ الفاتورة' }, dueDate: { t: 'date', label: 'تاريخ الاستحقاق' },
        poNo: { t: 'str', label: 'رقم أمر الشراء', dir: 'ltr' }, serviceRef: { t: 'str', label: 'مرجع عقد الخدمة', dir: 'ltr' },
        currency: { t: 'enum', label: 'العملة', opts: CUR },
        items: { t: 'items', label: 'بنود الفاتورة' },
        discount: { t: 'num', label: 'الخصم' }, taxRate: { t: 'num', label: 'نسبة الضريبة %' },
        subtotal: { t: 'num', label: 'المجموع الفرعي', calc: true }, tax: { t: 'num', label: 'الضريبة', calc: true }, total: { t: 'num', label: 'الإجمالي', calc: true }, paid: { t: 'num', label: 'المدفوع', calc: true },
        state: { t: 'enum', label: 'الوضع', opts: O(['draft', 'مسودة', ''], ['issued', 'صادرة', 'blue'], ['cancelled', 'ملغاة', 'red']) },
        notes: { t: 'text', label: 'ملاحظات الفاتورة' },
      } },
    payments: { module: 'finance', label: 'دفعة', search: ['no', 'ref'], num: { prefix: 'RCV', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم السند', auto: true }, invoiceId: { t: 'ref', label: 'الفاتورة', ref: 'invoices', req: true }, date: { t: 'date', label: 'التاريخ' },
        amount: { t: 'num', label: 'المبلغ', req: true },
        method: { t: 'enum', label: 'طريقة الدفع', opts: O(['transfer', 'تحويل بنكي'], ['cash', 'نقداً'], ['cheque', 'شيك'], ['card', 'بطاقة']) }, ref: { t: 'str', label: 'مرجع العملية', dir: 'ltr' }, note: { t: 'str', label: 'ملاحظة' } } },
    expenses: { module: 'finance', label: 'مصروف', search: ['no', 'note'], num: { prefix: 'EXP', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم المصروف', auto: true }, date: { t: 'date', label: 'التاريخ' },
        category: { t: 'enum', label: 'التصنيف', opts: O(['fuel', 'وقود'], ['salaries', 'رواتب'], ['rent', 'إيجارات'], ['maintenance', 'صيانة'], ['port', 'رسوم موانئ'], ['customs', 'رسوم جمركية'], ['office', 'مصاريف مكتبية'], ['marketing', 'تسويق'], ['other', 'أخرى']) },
        amount: { t: 'num', label: 'المبلغ', req: true }, currency: { t: 'enum', label: 'العملة', opts: CUR }, partyId: { t: 'ref', label: 'المورد', ref: 'parties' }, jobId: { t: 'ref', label: 'الشحنة', ref: 'jobs' },
        state: { t: 'enum', label: 'الحالة', opts: O(['paid', 'مدفوع', 'green'], ['pending', 'مستحق', 'amber']) }, note: { t: 'str', label: 'البيان' } } },
    branches: { module: 'branches', label: 'فرع أو وكيل', search: ['name', 'city', 'country', 'manager'],
      fields: { name: { t: 'str', label: 'الاسم', req: true }, kind: { t: 'enum', label: 'نوع الوحدة', opts: O(['branch', 'فرع'], ['agent', 'وكيل']) },
        country: { t: 'str', label: 'الدولة' }, city: { t: 'str', label: 'المدينة' }, address: { t: 'text', label: 'العنوان' },
        manager: { t: 'str', label: 'المدير أو المسؤول' }, phone: { t: 'str', label: 'الهاتف', dir: 'ltr' }, email: { t: 'str', label: 'البريد الإلكتروني', dir: 'ltr' },
        timezone: { t: 'str', label: 'المنطقة الزمنية', dir: 'ltr' }, currency: { t: 'enum', label: 'العملة', opts: CUR },
        commitment: { t: 'num', label: 'نسبة الالتزام %' },
        status: { t: 'enum', label: 'الحالة', opts: O(['active', 'نشط', 'green'], ['review', 'متوقف مؤقتاً', 'amber'], ['inactive', 'غير نشط', '']) } } },
    warehouses: { module: 'warehouse', label: 'مستودع', search: ['name', 'city'],
      fields: { name: { t: 'str', label: 'اسم المستودع', req: true }, branchId: { t: 'ref', label: 'الفرع', ref: 'branches' }, city: { t: 'str', label: 'المدينة' },
        area: { t: 'num', label: 'المساحة (م²)' }, rows: { t: 'int', label: 'عدد الصفوف في الخريطة' }, cols: { t: 'int', label: 'عدد المواقع في الصف' },
        dailyRate: { t: 'num', label: 'رسم التخزين اليومي الافتراضي' },
        status: { t: 'enum', label: 'الحالة', opts: O(['active', 'نشط', 'green'], ['inactive', 'متوقف', '']) } } },
    inventory: { module: 'warehouse', label: 'مخزون', search: ['ref', 'item', 'location', 'no'], num: { prefix: 'STK', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم السجل', auto: true }, warehouseId: { t: 'ref', label: 'المستودع', ref: 'warehouses', req: true }, partyId: { t: 'ref', label: 'العميل', ref: 'parties', req: true },
        jobId: { t: 'ref', label: 'الشحنة', ref: 'jobs' }, ref: { t: 'str', label: 'رقم الشحنة / المرجع', dir: 'ltr' }, item: { t: 'str', label: 'وصف الصنف' },
        qty: { t: 'num', label: 'الكمية' }, unit: { t: 'str', label: 'الوحدة' }, location: { t: 'str', label: 'موقع التخزين', dir: 'ltr' },
        dateIn: { t: 'date', label: 'تاريخ الدخول' }, dateOut: { t: 'date', label: 'تاريخ الخروج' }, dailyRate: { t: 'num', label: 'رسم التخزين اليومي' },
        state: { t: 'enum', label: 'الحالة', opts: O(['stored', 'مخزّن', 'green'], ['partial', 'صرف جزئي', 'blue'], ['hold', 'قيد المراجعة', 'amber'], ['released', 'تم الصرف', '']) } } },
    movements: { module: 'warehouse', label: 'حركة مستودع', search: ['ref', 'item', 'no'], num: { prefix: 'MOV', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم الحركة', auto: true }, type: { t: 'enum', label: 'نوع الحركة', opts: O(['in', 'استلام', 'green'], ['out', 'تسليم', 'blue']) },
        warehouseId: { t: 'ref', label: 'المستودع', ref: 'warehouses', req: true }, partyId: { t: 'ref', label: 'العميل', ref: 'parties' }, inventoryId: { t: 'ref', label: 'سجل المخزون', ref: 'inventory' },
        ref: { t: 'str', label: 'رقم الشحنة', dir: 'ltr' }, date: { t: 'date', label: 'التاريخ' }, time: { t: 'str', label: 'الوقت', dir: 'ltr' },
        item: { t: 'str', label: 'وصف الصنف' }, qty: { t: 'num', label: 'الكمية', req: true }, unit: { t: 'str', label: 'الوحدة' }, location: { t: 'str', label: 'موقع التخزين', dir: 'ltr' },
        handledBy: { t: 'str', label: 'الموظف المسؤول' }, notes: { t: 'text', label: 'ملاحظات' } } },
    trucks: { module: 'fleet', label: 'مركبة', search: ['plate', 'type', 'make', 'vin'],
      fields: { plate: { t: 'str', label: 'رقم اللوحة', req: true, dir: 'ltr' },
        type: { t: 'enum', label: 'نوع المركبة', opts: O(['curtain', 'شاحنة ستائر'], ['box', 'شاحنة مقفلة'], ['reefer', 'شاحنة مبردة'], ['flatbed', 'شاحنة مسطحة'], ['tipper', 'قلاب'], ['tanker', 'صهريج'], ['lowbed', 'لوبد'], ['van', 'فان'], ['tractor', 'رأس قاطر']) },
        make: { t: 'str', label: 'الصانع' }, model: { t: 'str', label: 'الطراز' }, year: { t: 'int', label: 'سنة الصنع' }, vin: { t: 'str', label: 'رقم الهيكل VIN', dir: 'ltr' },
        capacityKg: { t: 'num', label: 'الحمولة القصوى (كغ)' }, fuel: { t: 'enum', label: 'نوع الوقود', opts: O(['diesel', 'ديزل'], ['petrol', 'بنزين'], ['electric', 'كهرباء'], ['hybrid', 'هجين']) },
        odometer: { t: 'num', label: 'قراءة العداد (كم)' }, branchId: { t: 'ref', label: 'الفرع', ref: 'branches' }, driverId: { t: 'ref', label: 'السائق الحالي', ref: 'drivers' },
        location: { t: 'str', label: 'الموقع الحالي' }, trailer: { t: 'str', label: 'رقم المقطورة', dir: 'ltr' },
        status: { t: 'enum', label: 'الحالة', opts: O(['available', 'جاهزة', 'green'], ['on_trip', 'في الطريق', 'blue'], ['maintenance', 'تحتاج صيانة', 'amber'], ['inactive', 'متوقفة', 'red']) },
        licenseExpiry: { t: 'date', label: 'انتهاء الترخيص' }, insuranceExpiry: { t: 'date', label: 'انتهاء التأمين' }, inspectionExpiry: { t: 'date', label: 'انتهاء الفحص الفني' },
        notes: { t: 'text', label: 'ملاحظات' } } },
    drivers: { module: 'fleet', label: 'سائق', search: ['name', 'phone', 'licenseNo'],
      fields: { name: { t: 'str', label: 'اسم السائق', req: true }, phone: { t: 'str', label: 'الهاتف', dir: 'ltr' }, licenseNo: { t: 'str', label: 'رقم رخصة القيادة', dir: 'ltr' },
        licenseExpiry: { t: 'date', label: 'انتهاء رخصة القيادة' }, passportExpiry: { t: 'date', label: 'انتهاء جواز السفر' }, branchId: { t: 'ref', label: 'الفرع', ref: 'branches' },
        status: { t: 'enum', label: 'الحالة', opts: O(['available', 'متاح', 'green'], ['on_trip', 'في رحلة', 'blue'], ['off', 'غير متاح', '']) }, notes: { t: 'text', label: 'ملاحظات' } } },
    maintenance: { module: 'fleet', label: 'صيانة', search: ['vendor', 'notes'],
      fields: { truckId: { t: 'ref', label: 'المركبة', ref: 'trucks', req: true },
        type: { t: 'enum', label: 'نوع الصيانة', opts: O(['periodic', 'صيانة دورية'], ['repair', 'إصلاح عطل'], ['oil', 'تغيير زيت'], ['tires', 'إطارات'], ['inspection', 'فحص فني'], ['brakes', 'مكابح']) },
        due: { t: 'date', label: 'الموعد' }, date: { t: 'date', label: 'تاريخ التنفيذ' }, odometer: { t: 'num', label: 'العداد عند الصيانة' },
        cost: { t: 'num', label: 'التكلفة' }, vendor: { t: 'str', label: 'الورشة / المورد' },
        priority: { t: 'enum', label: 'الأولوية', opts: O(['normal', 'عادية', ''], ['urgent', 'عاجل', 'red'], ['soon', 'قريب', 'amber']) },
        state: { t: 'enum', label: 'الحالة', opts: O(['scheduled', 'مجدولة', 'blue'], ['in_progress', 'قيد التنفيذ', 'amber'], ['done', 'منجزة', 'green']) }, notes: { t: 'text', label: 'ملاحظات' } } },
    purchases: { module: 'procurement', label: 'طلب شراء', search: ['no', 'notes'], num: { prefix: 'PO', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم الطلب', auto: true }, kind: { t: 'enum', label: 'نوع المستند', opts: O(['request', 'طلب شراء'], ['order', 'أمر شراء'], ['bill', 'فاتورة مورد']) },
        partyId: { t: 'ref', label: 'المورد', ref: 'parties' },
        type: { t: 'enum', label: 'نوع الطلب', opts: O(['materials', 'مواد تشغيلية'], ['services', 'خدمات لوجستية'], ['equipment', 'معدات'], ['spare_parts', 'قطع غيار'], ['fuel', 'وقود'], ['office', 'مواد مكتبية'], ['cleaning', 'مواد تنظيف']) },
        items: { t: 'items', label: 'البنود' }, total: { t: 'num', label: 'القيمة', calc: true }, currency: { t: 'enum', label: 'العملة', opts: CUR },
        deliveryDate: { t: 'date', label: 'تاريخ التسليم' },
        state: { t: 'enum', label: 'الحالة', opts: O(['open', 'مفتوح', 'blue'], ['approval', 'قيد الموافقة', 'amber'], ['approved', 'معتمد', 'green'], ['received', 'مستلم', 'green'], ['rejected', 'مرفوض', 'red'], ['cancelled', 'ملغى', '']) },
        notes: { t: 'text', label: 'ملاحظات' } } },
    employees: { module: 'hr', label: 'موظف', search: ['name', 'empNo', 'email', 'title', 'department'], num: { prefix: 'EMP', field: 'empNo', pad: 4 },
      fields: { empNo: { t: 'str', label: 'الرقم الوظيفي', auto: true }, name: { t: 'str', label: 'الاسم الكامل', req: true }, nationalId: { t: 'str', label: 'رقم الهوية', dir: 'ltr' },
        birthDate: { t: 'date', label: 'تاريخ الميلاد' }, phone: { t: 'str', label: 'الهاتف', dir: 'ltr' }, email: { t: 'str', label: 'البريد الإلكتروني', dir: 'ltr' },
        branchId: { t: 'ref', label: 'الفرع', ref: 'branches' }, department: { t: 'enum', label: 'القسم', opts: O(['operations', 'العمليات'], ['sales', 'المبيعات'], ['finance', 'المالية'], ['customs', 'التخليص'], ['fleet', 'الأسطول'], ['warehouse', 'المستودعات'], ['hr', 'الموارد البشرية'], ['it', 'تقنية المعلومات'], ['management', 'الإدارة']) },
        title: { t: 'str', label: 'المسمى الوظيفي' }, hireDate: { t: 'date', label: 'تاريخ التعيين' },
        contractType: { t: 'enum', label: 'نوع العقد', opts: O(['permanent', 'دائم'], ['fixed', 'محدد المدة'], ['part_time', 'دوام جزئي'], ['trainee', 'متدرب']) }, contractEnd: { t: 'date', label: 'انتهاء العقد' },
        salary: { t: 'num', label: 'الراتب الأساسي' }, currency: { t: 'enum', label: 'عملة الراتب', opts: CUR },
        status: { t: 'enum', label: 'حالة الموظف', opts: O(['active', 'نشط', 'green'], ['leave', 'إجازة', 'amber'], ['terminated', 'منتهي الخدمة', 'red']) }, notes: { t: 'text', label: 'ملاحظات' } } },
    attendance: { module: 'hr', label: 'حضور', search: [],
      fields: { employeeId: { t: 'ref', label: 'الموظف', ref: 'employees', req: true }, date: { t: 'date', label: 'التاريخ', req: true },
        status: { t: 'enum', label: 'الحالة', opts: O(['present', 'حاضر', 'green'], ['late', 'متأخر', 'amber'], ['absent', 'غائب', 'red'], ['leave', 'إجازة', 'blue']) },
        checkIn: { t: 'str', label: 'وقت الدخول', dir: 'ltr' }, checkOut: { t: 'str', label: 'وقت الخروج', dir: 'ltr' }, note: { t: 'str', label: 'ملاحظة' } } },
    leaves: { module: 'hr', label: 'إجازة', search: ['note'],
      fields: { employeeId: { t: 'ref', label: 'الموظف', ref: 'employees', req: true },
        type: { t: 'enum', label: 'نوع الإجازة', opts: O(['annual', 'سنوية'], ['sick', 'مرضية'], ['unpaid', 'بدون راتب'], ['emergency', 'طارئة'], ['other', 'أخرى']) },
        from: { t: 'date', label: 'من', req: true }, to: { t: 'date', label: 'إلى', req: true },
        state: { t: 'enum', label: 'الحالة', opts: O(['pending', 'بانتظار الموافقة', 'amber'], ['approved', 'موافق عليها', 'green'], ['rejected', 'مرفوضة', 'red']) }, note: { t: 'str', label: 'ملاحظة' } } },
    documents: { module: 'documents', label: 'مستند', search: ['name', 'no', 'ref', 'fileName'], num: { prefix: 'DOC', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم المستند', auto: true }, name: { t: 'str', label: 'اسم المستند', req: true, full: true },
        type: { t: 'enum', label: 'نوع المستند', opts: O(['contract', 'عقود واتفاقيات'], ['invoice', 'فواتير ومدفوعات'], ['certificate', 'شهادات وتراخيص'], ['report', 'تقارير ومستندات مالية'], ['procedure', 'إجراءات تشغيل قياسية'], ['hr', 'موارد بشرية'], ['correspondence', 'مراسلات'], ['shipping', 'مستندات شحن'], ['other', 'أخرى']) },
        entity: { t: 'enum', label: 'مرتبط بـ', opts: O(['none', 'غير مرتبط'], ['jobs', 'شحنة'], ['parties', 'عميل / جهة'], ['contracts', 'عقد'], ['trucks', 'مركبة'], ['employees', 'موظف']) },
        entityId: { t: 'int', label: 'رقم السجل المرتبط' }, ref: { t: 'str', label: 'رقم المرجع', dir: 'ltr' }, version: { t: 'str', label: 'الإصدار', dir: 'ltr' },
        issueDate: { t: 'date', label: 'تاريخ الإصدار' }, expiryDate: { t: 'date', label: 'تاريخ الانتهاء' },
        state: { t: 'enum', label: 'الحالة', opts: O(['approved', 'معتمد', 'green'], ['review', 'بانتظار المراجعة', 'amber'], ['draft', 'مسودة', '']) },
        access: { t: 'enum', label: 'صلاحيات الوصول', opts: O(['all', 'كل الموظفين'], ['managers', 'المدراء فقط'], ['admin', 'مدير النظام فقط'], ['client', 'متاح للعميل في البوابة']) },
        fileId: { t: 'str', label: 'الملف' }, fileName: { t: 'str', label: 'اسم الملف' }, size: { t: 'int', label: 'الحجم' }, mime: { t: 'str', label: 'النوع' },
        notes: { t: 'text', label: 'ملاحظات' } } },
    complaints: { module: 'quality', label: 'بلاغ جودة', search: ['no', 'description'], num: { prefix: 'Q', field: 'no' },
      fields: { no: { t: 'str', label: 'رقم البلاغ', auto: true },
        source: { t: 'enum', label: 'مصدر الشكوى', opts: O(['customer', 'عميل'], ['employee', 'موظف'], ['internal', 'تدقيق داخلي'], ['supplier', 'مورد']) },
        partyId: { t: 'ref', label: 'العميل', ref: 'parties' }, jobId: { t: 'ref', label: 'الشحنة المرتبطة', ref: 'jobs' }, date: { t: 'date', label: 'تاريخ البلاغ' },
        type: { t: 'enum', label: 'نوع الشكوى', opts: O(['delay', 'تأخير'], ['damage', 'تلف أو فقد'], ['service', 'جودة الخدمة'], ['billing', 'الفواتير'], ['docs', 'المستندات'], ['other', 'أخرى']) },
        priority: { t: 'enum', label: 'الأولوية', opts: O(['low', 'منخفضة', ''], ['medium', 'متوسطة', 'amber'], ['high', 'عالية', 'red']) },
        owner: { t: 'user', label: 'المسؤول' }, due: { t: 'date', label: 'تاريخ الاستحقاق' },
        description: { t: 'text', label: 'وصف الشكوى', req: true },
        impact: { t: 'enum', label: 'التأثير على العمليات', opts: O(['none', 'لا يوجد تأثير', 'green'], ['limited', 'تأثير محدود', 'blue'], ['medium', 'تأثير متوسط', 'amber'], ['high', 'تأثير كبير', 'red']) },
        rootCause: { t: 'text', label: 'السبب الجذري' }, action: { t: 'text', label: 'الإجراء التصحيحي' },
        state: { t: 'enum', label: 'الحالة', opts: O(['new', 'جديدة', 'blue'], ['investigating', 'قيد التحقيق', 'amber'], ['action', 'قيد المعالجة', 'amber'], ['closed', 'مغلقة', 'green']) } } },
    reports: { module: 'reports', label: 'تقرير محفوظ', search: ['name'],
      fields: { name: { t: 'str', label: 'اسم التقرير', req: true },
        type: { t: 'enum', label: 'نوع التقرير', opts: O(['operational', 'تقرير تشغيلي'], ['financial', 'تقرير مالي'], ['fleet', 'تقرير الأسطول'], ['quality', 'تقرير الجودة'], ['customers', 'تقرير العملاء']) },
        from: { t: 'date', label: 'من' }, to: { t: 'date', label: 'إلى' }, branchId: { t: 'ref', label: 'الفرع', ref: 'branches' },
        mode: { t: 'enum', label: 'نوع الخدمة', opts: [['', 'كل الخدمات'], ...MODES] },
        schedule: { t: 'enum', label: 'تكرار الإرسال', opts: O(['none', 'بدون جدولة'], ['weekly', 'أسبوعي'], ['monthly', 'شهري']) } } },
  };

  const JOB_FLOW = {
    sea: ['draft', 'booked', 'loaded', 'sailed', 'arrived', 'clearing', 'released', 'delivered', 'closed'],
    land: ['draft', 'booked', 'loaded', 'in_transit', 'at_border', 'clearing', 'delivered', 'closed'],
    customs: ['draft', 'awaiting_docs', 'declared', 'inspection', 'duty_paid', 'released', 'closed'],
  };
  const JOB_STATUS = {
    draft: ['مسودة', ''], booked: ['تم الحجز', 'blue'], loaded: ['تم التحميل', 'blue'], sailed: ['أبحرت', 'blue'], arrived: ['وصلت', 'blue'],
    clearing: ['قيد التخليص', 'amber'], released: ['تم الإفراج', 'green'], delivered: ['تم التسليم', 'green'], closed: ['مغلق', ''], cancelled: ['ملغى', 'red'],
    in_transit: ['في الطريق', 'blue'], at_border: ['على الحدود', 'amber'], awaiting_docs: ['بانتظار المستندات', 'amber'], declared: ['تم تقديم البيان', 'blue'],
    inspection: ['قيد المعاينة', 'red'], duty_paid: ['تم دفع الرسوم', 'green'],
  };
  const family = (m) => (m === 'SE' || m === 'SI') ? 'sea' : (m === 'CC' ? 'customs' : 'land');

  const ROLE_DEFAULTS = {
    admin: { label: 'مدير النظام', all: 'rcud' },
    manager: { label: 'مدير عام', all: 'rcud', settings: 'r' },
    operations: { label: 'مشرف عمليات', crm: 'rcu', contracts: 'r', ops: 'rcud', customs: 'rcu', fleet: 'rcud', warehouse: 'rcud', documents: 'rcu', branches: 'r', reports: 'r', quality: 'rc' },
    sales: { label: 'مندوب مبيعات', crm: 'rcud', contracts: 'rcu', ops: 'rc', documents: 'rc', reports: 'r', branches: 'r' },
    customs: { label: 'مخلص جمركي', customs: 'rcu', ops: 'r', crm: 'r', documents: 'rcu' },
    accounts: { label: 'محاسب', finance: 'rcud', procurement: 'rcu', crm: 'r', contracts: 'r', ops: 'r', reports: 'r', documents: 'rc' },
    hr: { label: 'موارد بشرية', hr: 'rcud', documents: 'rcu', branches: 'r' },
    quality: { label: 'مسؤول الجودة', quality: 'rcud', ops: 'r', crm: 'r', documents: 'rcu', reports: 'r' },
    viewer: { label: 'مشاهدة فقط', crm: 'r', contracts: 'r', ops: 'r', customs: 'r', fleet: 'r', warehouse: 'r', documents: 'r', branches: 'r' },
    client: { label: 'عميل (بوابة العملاء)', portal: true },
  };

  const S = { MODULES, E, MODES, CUR, JOB_FLOW, JOB_STATUS, family, ROLE_DEFAULTS };
  if (typeof module !== 'undefined' && module.exports) module.exports = S; else root.SCHEMA = S;
})(typeof window !== 'undefined' ? window : globalThis);
